version: "3"
services:
  next-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    env_file:
      - .env.local
